app_tbl_actividades_detalle:
    resource: "@AppBundle/Controller/TblActividadesDetalleController.php"
    type:     annotation

aulas:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
