cursos_index:
    path:     /index
    defaults: { _controller: AppBundle:Cursos:index }

cursos_new:
    path:     /new
    defaults: { _controller: AppBundle:Cursos:newCurso }

cursos_new_save:
    path:     /newSave
    defaults: { _controller: AppBundle:Cursos:newCursoSave }

cursos_find:
    path:     /find
    defaults: { _controller: AppBundle:Cursos:findCursos }

cursos_add_curso_docente:
    path:     /save/{idCurso}
    defaults: { _controller: AppBundle:Cursos:saveCursoDocente }

cursos_edit_curso_docente:
    path:     /edit/{idCursoDocente,idCurso}
    defaults: { _controller: AppBundle:Cursos:editCursoDocente }

cursos_delete_curso_docente:
    path:     /delete/{idCursoDocente,idCurso}
    defaults: { _controller: AppBundle:Cursos:deleteCursoDocente }

cursos_add_actividad:
    path:     /saveActividad/{idCurso}
    defaults: { _controller: AppBundle:Cursos:saveActividad }

cursos_edit_actividad:
    path:     /editActividad/{idCurso,idActividad}
    defaults: { _controller: AppBundle:Cursos:editActividad }

cursos_delete_actividad:
    path:     /deleteActividad/{idCurso,idActividad}
    defaults: { _controller: AppBundle:Cursos:deleteActividad }        

cursos_gest_docentes:
    path:     /gestionarDocentes/{idCurso}
    defaults: { _controller: AppBundle:Cursos:gestionarDocentes }

cursos_gest_docentes_add:
    path:     /gestionarDocentesAdd/{idCurso}
    defaults: { _controller: AppBundle:Cursos:gestionarDocentesAdd }

cursos_gest_docentes_edit:
    path:     /gestionarDocentesEdit/{idCursoDocente}
    defaults: { _controller: AppBundle:Cursos:gestionarDocentesEdit }

cursos_gest_docentes_delete:
    path:     /gestionarDocentesDelete/{idCursoDocente}
    defaults: { _controller: AppBundle:Cursos:gestionarDocentesDelete }

cursos_gest_actividades:
    path:     /gestionarActividades/{idCurso}
    defaults: { _controller: AppBundle:Cursos:gestionarActividades }

cursos_gest_actividades_add:
    path:     /gestionarActividadesAdd/{idCurso}
    defaults: { _controller: AppBundle:Cursos:gestionarActividadesAdd }  

cursos_gest_actividades_edit:
    path:     /gestionarActividadesEdit/{idCurso,idActividad}
    defaults: { _controller: AppBundle:Cursos:gestionarActividadesEdit }

cursos_gest_actividades_delete:
    path:     /gestionarActividadesDelete/{idCurso,idActividad}
    defaults: { _controller: AppBundle:Cursos:gestionarActividadesDelete }

find_escuelas:
    path:     /findEscuelas
    defaults: { _controller: AppBundle:Cursos:findEscuelas }

aprobar_actividades_esc_init:
    path:     /aprobarActividadesEscInit
    defaults: { _controller: AppBundle:Cursos:aprobarActividadesEscInit }

aprobar_actividades_esc_find:
    path:     /aprobarActividadesEscFind
    defaults: { _controller: AppBundle:Cursos:aprobarActividadesEscFind }

aprobar_actividades_esc:
    path:     /aprobarActividadesEsc/{idActividad,idCiclo}
    defaults: { _controller: AppBundle:Cursos:aprobarActividadesEsc }   
     