aulas_index:
    resource: "@AppBundle/Resources/config/routes/index.yml"
    prefix:   /index

aulas_cursos:
    resource: "@AppBundle/Resources/config/routes/cursos.yml"
    prefix:   /cursos

aulas_aulas:
    resource: "@AppBundle/Resources/config/routes/aulas.yml"
    prefix:   /aulas