AppBundle\Entity\TblActividades:
    type: entity
    table: tbl_actividades
    indexes:
        fk_tbl_acti_relations_tbl_curs_:
            columns:
                - idcurso
        fk_tbl_acti_tipos_act_tbl_tipo_:
            columns:
                - idtipoactividad
    uniqueConstraints:
        tbl_actividades_pk:
            columns:
                - idactividad
    id:
        idactividad:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    manyToOne:
        idcurso:
            targetEntity: TblCursos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcurso:
                    referencedColumnName: idcurso
            orphanRemoval: false
        idtipoactividad:
            targetEntity: TblTiposActividades
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idtipoactividad:
                    referencedColumnName: idtipoactividad
            orphanRemoval: false
    lifecycleCallbacks: {  }
