AppBundle\Entity\TblCursos:
    type: entity
    table: tbl_cursos
    indexes:
        fk_tbl_curs_cursos_ma_tbl_mate_:
            columns:
                - idmateria
        fk_tbl_curs_cursos_ci_tbl_cicl_:
            columns:
                - idciclo
    uniqueConstraints:
        tbl_cursos_pk:
            columns:
                - idcurso
    id:
        idcurso:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombrecurso:
            type: string
            nullable: false
            length: 6
            fixed: false
    manyToOne:
        idciclo:
            targetEntity: TblCiclos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idciclo:
                    referencedColumnName: idciclo
            orphanRemoval: false
        idmateria:
            targetEntity: TblMaterias
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idmateria:
                    referencedColumnName: idmateria
            orphanRemoval: false
    lifecycleCallbacks: {  }
