AppBundle\Entity\TblMaterias:
    type: entity
    table: tbl_materias
    indexes:
        fk_tbl_mate_reference_tbl_escu_:
            columns:
                - idescuela
    uniqueConstraints:
        tbl_materias_pk:
            columns:
                - idmateria
    id:
        idmateria:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codigomateria:
            type: string
            nullable: false
            length: 25
            fixed: false
        nombremateria:
            type: string
            nullable: false
            length: 100
            fixed: false
        descripcionmateria:
            type: string
            nullable: true
            length: 200
            fixed: false
    manyToOne:
        idescuela:
            targetEntity: TblEscuelas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idescuela:
                    referencedColumnName: idescuela
            orphanRemoval: false
    lifecycleCallbacks: {  }
