AppBundle\Entity\TblMenusub:
    type: entity
    table: tbl_menusub
    indexes:
        fk_tbl_menu_fk_submen_tbl_menu_:
            columns:
                - idmenu
    uniqueConstraints:
        tbl_menusub_pk:
            columns:
                - idsubmenu
    id:
        idsubmenu:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombresubmenu:
            type: string
            nullable: true
            length: 200
            fixed: false
        url:
            type: string
            nullable: true
            length: 200
            fixed: false
        fechaalta:
            type: date
            nullable: true
    manyToOne:
        idmenu:
            targetEntity: TblMenus
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idmenu:
                    referencedColumnName: idmenu
            orphanRemoval: false
    lifecycleCallbacks: {  }
