AppBundle\Entity\TblPerfil:
    type: entity
    table: tbl_perfil
    uniqueConstraints:
        tbl_perfil_pk:
            columns:
                - idperfil
    id:
        idperfil:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreperfil:
            type: string
            nullable: true
            length: 50
            fixed: false
        descripcion:
            type: string
            nullable: true
            length: 100
            fixed: false
        fechaalta:
            type: date
            nullable: true
    manyToMany:
        idusuario:
            targetEntity: TblUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: idperfil
            joinTable:
                name: tbl_usuariosperfiles
                joinColumns:
                    -
                        name: idperfil
                        referencedColumnName: idperfil
                inverseJoinColumns:
                    -
                        name: idusuario
                        referencedColumnName: idusuario
            orderBy: null
    lifecycleCallbacks: {  }
