AppBundle\Entity\TblPerfildetalle:
    type: entity
    table: tbl_perfildetalle
    indexes:
        fk_perfildetalle_menu_fk:
            columns:
                - tbl_idmenu
        fk_perfildetalle_submenu_fk:
            columns:
                - tbl_idsubmenu
        fk_perfildetalle_perfil_fk:
            columns:
                - tbl_idperfil
    uniqueConstraints:
        ak_fk_perfildetalle_m_tbl_perf:
            columns:
                - idmenu
        ak_fk_perfildetalle_s_tbl_perf:
            columns:
                - idsubmenu
        ak_fk_perfildetalle_p_tbl_perf:
            columns:
                - idperfil
        tbl_perfildetalle_pk:
            columns:
                - idperfildetalle
    id:
        idperfildetalle:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        idperfil:
            type: integer
            nullable: false
            unsigned: false
        idmenu:
            type: integer
            nullable: true
            unsigned: false
        idsubmenu:
            type: integer
            nullable: true
            unsigned: false
        comentario:
            type: string
            nullable: true
            length: 100
            fixed: false
        fechaalta:
            type: date
            nullable: true
    lifecycleCallbacks: {  }
