AppBundle\Entity\TblPerfildetalle:
    type: entity
    table: tbl_perfildetalle
    indexes:
        fk_tbl_perf_fk_perfil_tbl_menu_:
            columns:
                - idmenu
        fk_tbl_perf_fk_perfil_tbl_menu2:
            columns:
                - idsubmenu
        fk_tbl_perf_fk_perfil_tbl_perf_:
            columns:
                - idperfil
    uniqueConstraints:
        tbl_perfildetalle_pk:
            columns:
                - idperfildetalle
    id:
        idperfildetalle:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        comentario:
            type: string
            nullable: true
            length: 100
            fixed: false
        fechaalta:
            type: date
            nullable: true
    manyToOne:
        idmenu:
            targetEntity: TblMenus
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idmenu:
                    referencedColumnName: idmenu
            orphanRemoval: false
        idsubmenu:
            targetEntity: TblMenusub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idsubmenu:
                    referencedColumnName: idsubmenu
            orphanRemoval: false
        idperfil:
            targetEntity: TblPerfil
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idperfil:
                    referencedColumnName: idperfil
            orphanRemoval: false
    lifecycleCallbacks: {  }
